name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10.6'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install coverage coverage[toml] matplotlib==3.7.1 numpy==1.21.6 scipy==1.11.1 jsoncomparison pypulseq@git+https://github.com/tblazey/pypulseq#egg=dev PyQt5 nibabel==4.0.1 fslpy twixtools@git+https://github.com/pehses/twixtools#egg=master
    - name: Run tests and collect coverage
      run: |
        export QT_QPA_PLATFORM=offscreen
        coverage run -m unittest discover -s tests
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
