name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run tests and collect coverage
      run: coverage run -m unittest discover -s tests
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
